### ISSUE TITLE
Undocument op `execname`

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/nqp#469] opened 2018-06-26 08:12 UTC
https://github.com/perl6/nqp/blob/50bb7de4da1e90907f42fa86ee68884e79c71811/src/vm/moar/QAST/QASTOperationsMAST.nqp#L2908

So, what is the op used for?

**Comment by zoffixznet** [comment] 2018-06-26 10:50
Dupe of https://github.com/perl6/nqp/issues/293 which lists about 200 test failures for undocumented ops

**Comment by jnthn** [comment] 2018-06-26 15:29
It's used to implement `$*EXECUTABLE` in Perl 6, and is the name of the current "executable". So if you run `./perl6-m ....` then it'll be the `./perl6-m`. It's actually set at present by passing a `--execname=` argument to MoarVM, since `perl6` is actually a shell script. But when we do get to providing a fake executable for `perl6` instead, then it'd just initialize it to `argv[0]`.

**Closed** 2018-06-26 16:23 UTC
